name: Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3  
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.2'
      
      # Check if node_modules folder exists and remove it if it does
      - name: Check if node_modules exists
        run: |
          if [ -d "backend/node_modules" ]; then
            rm -rf backend/node_modules
          fi
      
      # Install dependencies and restart services
      - name: Install dependencies and restart services
        run: |
          cd backend
          npm i
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart