name: Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3  
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.2'
      
      # Build the backend, remove node_moduels, restart pm2 and nginx services
      - name: Build Backend
        run: |
          cd backend
          rm -r node_modules/
          npm i
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart